# Generated by Django 5.2.8 on 2025-11-13 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_page_content_alter_page_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='category',
            field=models.CharField(choices=[('BIO', 'Biología'), ('CAL', 'Cálculo'), ('CIE', 'Ciencias'), ('NOV', 'Novedades'), ('OTR', 'Otros')], default='OTR', max_length=3, verbose_name='Categoría'),
        ),
    ]
