# Generated by Django 5.2.8 on 2025-11-14 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='Biografía')),
                ('location', models.CharField(blank=True, max_length=30, verbose_name='Ubicación (Ej: UNSAM)')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('title', models.CharField(choices=[('Estudiante', 'Estudiante'), ('Ingeniero', 'Ingeniero/a'), ('Profesor', 'Profesor/a'), ('Investigador', 'Investigador/a')], default='Estudiante', max_length=30, verbose_name='Título/Rol')),
                ('image', models.ImageField(blank=True, default='profile_pics/default.jpg', upload_to='profile_pics', verbose_name='Foto de Perfil')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
